---
title: "dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r data}
data("ny_noaa")


ny_noaa = 
  ny_noaa %>%
  na.omit() %>%
 
   filter( 
    format(as.Date(date, format = "%Y-%m-%d"), "%Y") == "1994"
  ) %>%
  sample_n(200) 
  
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
scatter_plot = ny_noaa %>% 
  ggplot(aes(x = tmin, y = tmax, color = snow)) +
  geom_point(alpha = 0.5) +
  scale_color_viridis() +
  coord_cartesian() +
  theme_classic() +
  theme(axis.text.x  = element_text(angle = 90, hjust = 1)) +
  ggtitle("Relationship Between Minimum Temp & Maximum Temp in NY,1994")

ggplotly(scatter_plot)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
ny_noaa %>%
  mutate( month = format(as.Date(date, format = "%Y-%m-%d"), "%m")) %>%
   
  plot_ly(y = ~prcp, color = ~month, type = "box",
          colors = "Set2") %>%
  layout(title = "Relationship Between Precipitation and Month in NY, 1994")
```

### Chart C

```{r}
ny_noaa %>%
  count(id) %>%
  mutate(id = fct_reorder(id, n)) %>%
  plot_ly(x = ~id, y = ~n, type = "bar") %>%
  layout(title = "Number of Observations Made Per Weather Station in NY")
```