---
title: "thoughts"
output: 
  html_document:
    css: style.css
---

What makes life worth living?

Candies, friends, lovers, chocolate, work...?

A lot of times life feels like a race; you do not exactly know where you are heading but you are afraid to stop running as it feels like a race. It is easy to want what others want, but hard to know what YOU really want.

"An unexamined life if not worth living." said Socrates. Life seems to be the ultimate messy thing that is so hard to be examined objectively. Overall, we seem to examine people by their education, job title, familial and social connections and outward appearance. We tend to think that Stanford graduates have a better life than people from non-pretigious programs. We tend to think that someone working at Google has a better life than a cashier at Walmart. We tend to think that good-looking people have a better life than most. And we look at our own life through similar lens. Instead of examining our own life, we try to carve out a life that is perceived to be "good". However, what is "good" anyways?

For most people, pleasure is good. After all, that is why so many people are addicted to drugs that can make your brain emit the pleasure chemicals. We desire pleasure, from basic food and housing to sex, power and achievements. The problem is, pleasure also follows the law of diminishing returns. No pleasure can last FOREVER and the pursuit of pleasure will never be fully completed - until we die and turn into zombies who cannot feel any pleasure at all. To some, this might further confirm the importance of pleasure in life as we only get to experience pleasure when we are alive. So, is life about optimizing pleasure and avoiding pain?

There is a temptation to say yes - yet some experiences in life make me think deeper about "pleasure". I remember feeling the heavenly appeals of music as a young kid; the peace and coziness from sunrays radiating through tree leaves; the deep feeling of love at some little moments. Those feelings are different, like suddent misaligned notes from a music score that draws you out of current time and space. Maybe it is the spirit. Something within us that is paradoxically bigger than us. Maybe it is the eternal, as opposed to our transient flesh-body...

Can we program our own mind to have more of those serene states? To me, those moments, the moments where I feel the eternity, is what makes life truly worth living...

Poem to share:
The Moment
by Marie Howe

Oh, the coming-out-of-nowhere moment
when, nothing
happens
no what-have-I-to-do-today-list

maybe half a moment
the rush of traffic stops.
The whir of I should be, I should be, I should be
slows to silence,
the white cotton curtains hanging still.



